name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Ya master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        # Yahan humne aapke domain ka sahi folder path set kar diya hai 👇
        server-dir: notesbynain.xo.je/htdocs/