name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Agar aapki branch ka naam 'master' hai to yahan master kar dena

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21                        # InfinityFree ka standard FTP port
        protocol: ftp                   # Secure connection initialization ke liye
        server-dir: htdocs/             # InfinityFree ka main web folder